### ISSUE TITLE
$IS_SUDO is unnecessarily complex

### ISSUE THREAD

**Issue by woodruffw** [guarinogabriel/mac-cli#10]
First of all, great work on this script. I saw it on HN and it looks very useful :smile: 

You populate `IS_SUDO` as follows:
```bash
IS_SUDO=$(sudo -n uptime 2>&1|grep "load"|wc -l)
```

This works, but it's more fragile than just checking whether the `uid` is 0, which would imply that the script is being run as `root`:

```bash
IS_SUDO=$(id -u)
```

Alternatively, `bash` sets `$EUID` to the same value.

Conditions like

```bash
if [ ${IS_SUDO} -gt 0 ]; then
```

should then become

```bash
if [ ${IS_SUDO} -eq 0 ]; then # or just use ${EUID} directly
```

**Comment by guarinogabriel** [comment]
@woodruffw Thanks for your kind words! It's great to have your feedback on the project.

I will update the $IS_SUDO logic based on your suggestion.

**Comment by woodruffw** [comment]
No problem, happy to help!

**Comment by guarinogabriel** [comment]
@woodruffw Your suggestion has been implemented on the following commit: https://github.com/guarinogabriel/mac-cli/commit/41381e5357ae9a5040ffa9d3454828b6d9f52a58

Thanks!
