### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by pahakalle** [guarinogabriel/Mac-CLI#103]
might i suggest adding npm-up as a way to speed up npm update 😄 
Link to it: [Npm-up](https://www.npmjs.com/package/npm-up)

**Comment by guarinogabriel** [comment]
Hi there,

Thanks for your suggestion. Since this is a very old Github Issue, I am proceeding by closing it but feel free to create Pull Requests for the improvements you would like to make on the project.
