### ISSUE TITLE
/usr/local/bin is not present on a clean macOS/OS X install

### ISSUE THREAD

**Issue by christopheranderton** [guarinogabriel/Mac-CLI#105]
On a clean install of macOS/OS X, the directory `bin` `(/usr/local/bin)` is not present per default. The Mac-CLI installer should check if `/usr/local/bin` is present, and if not, create the directory in the beginning of the script (Homebrew and others will create the directory if not present, but that's too late).

If not, the installer will output errors of missing directories making some things break. 

**Pastebin URL to the whole install procedure with errors (and enviroment data):**  http://pastebin.com/Asj0beYW

Cheers! Keep up the good work!

**Comment by jbhv12** [comment]
I have created a new pull request and solved this issue.

**Comment by guarinogabriel** [comment]
@jbhv12 Thanks for your contribution!
