### ISSUE TITLE
Make mysql an optional setup

### ISSUE THREAD

**Issue by tal** [guarinogabriel/Mac-CLI#114]
It's a little confusing for those of us who don't care about the LAMP or MySQL features of the tool to have to set up the mysql features. It's also alienating for those who don't understand why it's required.

**Comment by tero** [comment]
Agreed. Also Composer could be optional, because everyone isn't using php.

**Comment by guarinogabriel** [comment]
Hello there!

Thanks for your suggestions. Mac-CLI is a command-line tool for developers, that is why I included those utilities by default.

If you would like to make it optional, you can move forward with a pull request and I will be glad to get that merged if the option to included LAMP+MySQL is included in the wizard.
