### ISSUE TITLE
Speedtest not working

### ISSUE THREAD

**Issue by mcartagenah** [guarinogabriel/Mac-CLI#117]
I installed everything with Mac-CLI, but every time I use `mac speedtest` it asks me if I want to install the Speed Test Utility, I put yes and it installs fast-cli and thats it...

![image](https://cloud.githubusercontent.com/assets/10224074/22223441/c348eaa0-e199-11e6-818f-c26b1edd8729.png)

**Comment by guarinogabriel** [comment]
Hi @manuel0097,

Could you please run the following command?
`npm install --global fast-cli`

Please let me know if the installation was successful.

**Comment by manuel0097** [comment]
Hi @guarinogabriel,
The installation was successful but the problem persists.

**Comment by carolineartz** [comment]
@mcartagenah just took out a PR for this: https://github.com/guarinogabriel/Mac-CLI/pull/151

**Comment by oalhait** [comment]
Bump. Hasn't been working for me since December.

**Comment by guarinogabriel** [comment]
Hi there,

I am closing this issue since the speed test command has been updated with the following native command from MacOS: 
`networkQuality -v`
