### ISSUE TITLE
eject-all not working

### ISSUE THREAD

**Issue by aspirewit** [guarinogabriel/Mac-CLI#119]
```
➜  ~ mac eject-all
53:63: execution error: The variable executable is not defined. (-2753)
```

OS:
macOS Sierra
Version 10.12.3 (16D32)

**Comment by begroff** [comment]
It looks like the osascript command is wrong. It currently is "osascript -e 'tell application 'Finder' to eject (every disk whose **executable** is true)' but it should be osascript -e 'tell application "Finder" to eject (every disk whose **ejectable** is true)'. I'm going to see if I can fix and submit pull request.
