### ISSUE TITLE
fish-shell command line completion doesn't work

### ISSUE THREAD

**Issue by douglascamata** [guarinogabriel/Mac-CLI#120]
I just installed this and cannot get the command line completion to work on fish.

**Comment by douglascamata** [comment]
Updating: I wasn't prompted to install `fish` completions, but `bash` completions instead.

**Comment by douglascamata** [comment]
One more update: when completing a command, like `mac git:<tab><tab>` it shows folder names... I don't think it should. Only `git` subcommands should be shown.

**Comment by guarinogabriel** [comment]
Hi there,

Since this is a very old Github Issue, I am proceeding by closing it but feel free to create Pull Requests for the improvements or fixes you would like to make on the project.
