### ISSUE TITLE
[feature request] shortcut to update mac-cli

### ISSUE THREAD

**Issue by sg-s** [guarinogabriel/Mac-CLI#121]
Hi, Instead of:

```
sh -c "$(curl -fsSL https://raw.githubusercontent.com/guarinogabriel/mac-cli/master/mac-cli/tools/update)"
```

can we simply `mac upgrade` ?

**Comment by guarinogabriel** [comment]
Great suggestion!

The following commands have been added in this commit: https://github.com/guarinogabriel/Mac-CLI/commit/3d3a68e59cba8391772ed35388098523a0f48e1c

`mac upgrade`
`mac uninstall`

Best regards.
Gabriel

**Comment by sg-s** [comment]
thanks! that's great!
