### ISSUE TITLE
Can't change preferred editor

### ISSUE THREAD

**Issue by revolter** [guarinogabriel/Mac-CLI#126]
Following the README's configuration instructions, I opened the `mac` file to change my preferred editor, but that line is:

    export pref_editor="${pref_Editor}"

Where is the `pref_Editor` defined?

**Comment by berryamin** [comment]
pref_editor is prompted when script mac-cli/tools/install is called,
and then, it's stored inside 'mac' script

Here is the relevant code from mac-cli/tools/install:

<pre>
    echo "${LIGHTGREEN}Please enter your favourite text editor (by entering the command that opens your favourite editor. i.e: nano):"
    echo "${NC}Press enter without any value to keep default: vi"
    read pref_editor
    if [ ! -z "$pref_editor" -a "$pref_editor" != " " ]; then
        LC_CTYPE=C sed -i'' -e 's#pref_editor="vi"#pref_editor="${pref_Editor}"#g' "$PACKAGE_DIRECTORY/mac-cli/mac"
    fi
</pre>

**Comment by revolter** [comment]
Understood, thank you!
