### ISSUE TITLE
Add yarn upgrade to mac update

### ISSUE THREAD

**Issue by pahakalle** [guarinogabriel/Mac-CLI#135]
Now that most users use yarn adding it to update would be a good idea.

**Comment by cucumbur** [comment]
I have this in my fork im working on, private repo until its done enough for primetime though

**Comment by guarinogabriel** [comment]
@pahakalle @cucumbur – Thanks for your feedback!

Added by @dancyfits on the following PR: https://github.com/guarinogabriel/Mac-CLI/pull/138
