### ISSUE TITLE
VPN command

### ISSUE THREAD

**Issue by jcalonso** [guarinogabriel/Mac-CLI#143]
Hi!

I was looking without luck for a VPN command to connect to any of my current VPN connections. Any ideas how to achieve this?

Thanks!

**Comment by pahakalle** [comment]
Why not just use [Tunnelblick](https://tunnelblick.net/) ?

**Comment by jcalonso** [comment]
Uhm, as far as I know, Tunnelblick is just for OpenVPN. I use Cisco IPsec which I configure with the normal MacOS VPN configurator.
And my use case was because normally I do something like:
```
jcalonso@macbook:~⟫ ssh some-work-server
ssh: Could not resolve hostname some-work-server...
#Crap! I forgot to connect to the work VPN, so it would be nice to do:
jcalonso@macbook:~⟫ mac vpn:connect work
jcalonso@macbook:~⟫ ssh some-work-server
...
```

**Comment by pahakalle** [comment]
Totally forgot about IPsec. 
Something like [this](https://superuser.com/a/736859) might work for you, and if it does could you tell me, so i (or someone else) could add it as a `mac vpn:connect` command

**Comment by jcalonso** [comment]
thanks @pahakalle works perfect!
