### ISSUE TITLE
"sudo gem update --system" and "sudo gem update" causes problem with rbenv/RVM installed

### ISSUE THREAD

**Issue by lebensterben** [guarinogabriel/Mac-CLI#148]
Hi,

I found that after the first successful "mac update" operation, it always fails at "sudo gem update --system" and "sudo gem update". I found that it could be manually fixed by reinstalling those gems with "gem install XXX --user-install" and "mac update" would work for **once** and the same problem came back. ( Though gem update --system always fails.)

I later found out that this is due to that I replaced the system-ruby (version 2.3.x) with the one I installed with "rbenv". And  it turns out that if "rbenv" or "RVM" is used, it would broke the ruby installation if sudo is used during upgrades.

An upgrade to mac-cli is needed s.t. during the original installation, the script should check whether rbenv/RVM is used and prompt to ask the user whether to elevate the privilege with sudo command during updates. And for existing users, there need to be an option in /usr/local/bin/mac file s.t. they could specify whether sudo is used or not.

Thanks.

**Comment by pahakalle** [comment]
Is there a need to **ask** for sudo if rbenv/RVM is used?
