### ISSUE TITLE
Uninstall needs to uninstall all installed packages too

### ISSUE THREAD

**Issue by deiga** [guarinogabriel/Mac-CLI#152]

**Comment by guarinogabriel** [comment]
@deiga - Thanks for your suggestion. For now, Mac-CLI will not include the ability to uninstall those packages since they might be manually installed by the user and we would be removing them.

**Comment by deiga** [comment]
@guarinogabriel fair enough.
Could it at least list all the packages it installed, so that one could manually uninstall them?
It was a pain trying to uninstall everything that came with mac-cli
