### ISSUE TITLE
'pip install' should use --user flag on MacOS Mojave

### ISSUE THREAD

**Issue by Sirclicksalot** [guarinogabriel/Mac-CLI#159]
In trying to install/use mac-cli on a brand new install of Mojave (10.14.2), I was unable to install glances (resolved by installing via `brew install glances`) or successfully run the pip portion of `mac update` with the command as currently formatted. 

Specifically;
`pip list --outdated --format=freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U`
results in a whole long list of
`Could not install packages due to an EnvironmentError: 
[('/System/Library/Frameworks/Python.framework/Versions/2.7/....', '/private/var/folders/...', "[Errno 1] Operation not permitted:`
whereas substituting `pip install --user` worked like a charm.

I know I could try to find/make these changes, and submit a PR, but I'm still not exactly a paragon of confidence in coding/github/etc. So I'm just letting anyone know who might care.

**Comment by bskiefer** [comment]
+1

**Comment by ChasLui** [comment]
+1
