### ISSUE TITLE
Feature request: completion

### ISSUE THREAD

**Issue by berndblume** [guarinogabriel/Mac-CLI#17]
I'd love to see zsh command completion. Other people might like bash command completion.

**Comment by guarinogabriel** [comment]
I agree with you. I'd love to see command completion as well.

That is the next big update for the project once we complete the modularity feature:
https://github.com/guarinogabriel/mac-cli/issues/3

**Comment by guarinogabriel** [comment]
Bash completion has been added on the following commit:
https://github.com/guarinogabriel/Mac-CLI/commit/c490b05273f70e4b4f2c0ce5d2d40a4c71d0eb9b

**Comment by wookayin** [comment]
How about ZSH?
