### ISSUE TITLE
`mac presentation` destroyed whole flow 

### ISSUE THREAD

**Issue by idarbuashvili** [guarinogabriel/Mac-CLI#176]
Is anyone maintaining this repository at all? `mac presentation` command basically moved all my download and desktop files to trash and I have no idea how to get those back, can't find an answer anywhere. If this repository is no more maintained PLEASE write that, otherwise many other people will have similar problems.

**Comment by idarbuashvili** [comment]
Anyone having the same issues, in the trash under context menu, make sure to have `Use Groups` unchecked and set sorting to `Date Added`, then put back all files that have `Date Added` today. Regarding `mac presentation` this command, I have no idea how such a tool can be offering a command with such a destructive result, without any option to bring everything back. Also `mac presentation` is causing remapping of keyboard and without restart, it is no way to get correct keyboard mapping back, this issue has been here for the last 3 years and no one has done anything to fix it. So again, thanks for the repo, but if no one is maintaining this, JUST writes it in README. I will be removing this tool from my machine, as it's unstable, unmaintained and who knows what other, more destructive results might some commands give. Thank you again and have a good day!

**Comment by guarinogabriel** [comment]
Hi there,


I understand how frustrating can be to not locate the files from your Desktop or Downloads folders. That command specifically clarifies in the documentation that it sends those files to the Trash, that is why it can be restored from that location.

That was the original idea from the command to provide a clean view for the Desktop and Downloads directories, but I just removed that logic since it should be a decision from the user to remove those files or not.


Thanks for your feedback.

**Comment by idarbuashvili** [comment]
Hi @guarinogabriel, yeah the above is stated in docs, but I had hopes that there would be a flag or command on top causing everything to get back. Until that will be one of the available options for the tool, this command should be either disabled or as you wrote not move files without the user agreeing first. With closing down applications same here, but that is ok, I have no issue reopening them after if I want to go presentation. Thanks for working on the repo, it's an awesome project. BTW is this repo in active development, if it is, I would love to take on some of the issues and take part :))
