### ISSUE TITLE
Error on mac update

### ISSUE THREAD

**Issue by lbonvarl** [guarinogabriel/Mac-CLI#190]
Hello,
The last part of the command fails as below:

```
mac update
(....)

Updating installed pip packages...
pip list --outdated --format=freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U

ERROR: List format 'freeze' can not be used with the --outdated option.
Updating installed pip3 packages...
pip3 list --outdated --format=freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip3 install -U

ERROR: List format 'freeze' can not be used with the --outdated option.
```

**Comment by fugitiveMedia** [comment]
I'm very impress with your tool coming from Multiple Package Manager(mpm). I have 3 macs (macos 13.3.1, 12.6.5, 10.13.6). I have latest pip installed for pip3, pip. All the macs show the error about --format=freeze crashing on that command for pip and pip3.  https://stackoverflow.com/questions/2720014/how-to-upgrade-all-python-packages-with-pip seems to have a mess of output but words with even though it's not updating only outdated modules but everything(yeah a bit problematic). There are other paths than just saying wontfix, sorry. Guess I'll go back to if that is the response to the issue
