### ISSUE TITLE
Adding plugin

### ISSUE THREAD

**Issue by LudicrousSpeed** [guarinogabriel/Mac-CLI#194]
To add my own plugin locally do you just add a file named after the command in '/usr/local/bin/mac-cli/plugins'?

I tried copying an existing file to a new name and this didn't appear to work.

Thanks

**Comment by guarinogabriel** [comment]
Hi there – I'm not sure how you have implemented the additional plugin, but you can check the following search results to see an example of how the "find:recent" command was implemented:
https://github.com/search?q=repo%3Aguarinogabriel%2FMac-CLI%20find%3Arecent&type=code

Hope that helps!
