### ISSUE TITLE
Pip errors when running script

### ISSUE THREAD

**Issue by kevdogg** [guarinogabriel/Mac-CLI#197]
I'm sure there is a workaround however I'm getting the following:

```
Updating installed pip packages...
pip list --outdated --format=freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U

ERROR: List format 'freeze' cannot be used with the --outdated option.
Updating installed pip3 packages...
pip3 list --outdated --format=freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip3 install -U

ERROR: List format 'freeze' cannot be used with the --outdated option.

```

I'm running the following:

```
$ pip --version
pip 24.2 from /opt/homebrew/lib/python3.11/site-packages/pip (python 3.11)
```

**Comment by martinsnygg** [comment]
Hey @kevdogg this seems to work:

pip list --outdated --format=json | python3 -c "import json, sys; print('\n'.join([p['name'] for p in json.load(sys.stdin)]))" | xargs -n1 pip install -U

pip3 list --outdated --format=json | python3 -c "import json, sys; print('\n'.join([p['name'] for p in json.load(sys.stdin)]))" | xargs -n1 pip3 install -U
