### ISSUE TITLE
Detect NVM

### ISSUE THREAD

**Issue by michaelowens** [guarinogabriel/Mac-CLI#23]
Currently certain path's are hardcoded (e.g. speedtest). When using NVM, you have a path variable `$NVM_BIN` available to get the path to the correct node_modules/bin folder. Would be nice to detect if this is present and use that instead, so it works properly for NVM users.

e.g. current hardcoded path vs `$NVM_BIN`:
```
$ ls /usr/local/lib/node_modules/
npm

$ ls $NVM_BIN
asar                     babel-external-helpers   bode-debug               elm-oracle               ied                      imageOptimBashLib        node-debug               npm                      pngquant                 wilfred
babel                    babel-node               boiler                   eslint                   imageOptim               ncu                      node-inspector           npm-check-updates        speed-test
babel-doctor             babel-node-debug         electron                 gulp                     imageOptimAppleScriptLib node                     nodemon                  nsp                      vue
```

(As you can see that includes speed-test)

**Comment by guarinogabriel** [comment]
@michaelowens Awesome! Thanks for suggesting this. The improvement will be implemented soon.

**Comment by guarinogabriel** [comment]
@michaelowens Could you please contribute on the project by adding this feature?
