### ISSUE TITLE
mac speedtest not working

### ISSUE THREAD

**Issue by berndblume** [guarinogabriel/Mac-CLI#24]
I tried to run `mac speedtest`, then got an error message saying npm is not installed. So I installed nvm and node. Question: `mac install:all` is supposed to install all dependencies, why not node? Then I ran `mac speedtest` again. The tool asked my if I want to install the speedtest tool. I was asking myself why this happens because I did a `mac install:all`, which is supposed to install all dependencies. After confirming "Yes", the speed-test utility was being installed, but no speedtest was run. So I ran `mac speedtest` again and ended up in an infinite loop.
```
bb@broom:~ % mac speedtest
Do you want to install the Speed Test utility? (https://github.com/sindresorhus/speed-test) (Yes / No)Yes
/usr/local/Cellar/nvm/0.31.2/versions/node/v6.2.2/bin/speed-test -> /usr/local/Cellar/nvm/0.31.2/versions/node/v6.2.2/lib/node_modules/speed-test/cli.js
/usr/local/Cellar/nvm/0.31.2/versions/node/v6.2.2/lib
└── speed-test@1.7.0 

bb@broom:~ % mac speedtest
Do you want to install the Speed Test utility? (https://github.com/sindresorhus/speed-test) (Yes / No)Yes
/usr/local/Cellar/nvm/0.31.2/versions/node/v6.2.2/bin/speed-test -> /usr/local/Cellar/nvm/0.31.2/versions/node/v6.2.2/lib/node_modules/speed-test/cli.js
/usr/local/Cellar/nvm/0.31.2/versions/node/v6.2.2/lib
└── speed-test@1.7.0 

bb@broom:~ % mac speedtest
Do you want to install the Speed Test utility? (https://github.com/sindresorhus/speed-test) (Yes / No)
```

**Comment by debugger22** [comment]
Could you please try with `yes`? Worked for me.

**Comment by berndblume** [comment]
You mean `yes` instead of `Yes`?
I tried, same effect:
```
bb@broom:~ % mac speedtest      
Do you want to install the Speed Test utility? (https://github.com/sindresorhus/speed-test) (Yes / No)yes
/usr/local/Cellar/nvm/0.31.2/versions/node/v6.2.2/bin/speed-test -> /usr/local/Cellar/nvm/0.31.2/versions/node/v6.2.2/lib/node_modules/speed-test/cli.js
/usr/local/Cellar/nvm/0.31.2/versions/node/v6.2.2/lib
└── speed-test@1.7.0 

bb@broom:~ % mac speedtest
Do you want to install the Speed Test utility? (https://github.com/sindresorhus/speed-test) (Yes / No)yes
/usr/local/Cellar/nvm/0.31.2/versions/node/v6.2.2/bin/speed-test -> /usr/local/Cellar/nvm/0.31.2/versions/node/v6.2.2/lib/node_modules/speed-test/cli.js
/usr/local/Cellar/nvm/0.31.2/versions/node/v6.2.2/lib
└── speed-test@1.7.0 

bb@broom:~ % 
```
Maybe some problem with nvm?

**Comment by Initsogar** [comment]
I'm having the same issue. Everytime I try to execute `mac speedtest` it ask me if I wanna install the utility.

**Comment by guarinogabriel** [comment]
@berndblume Thanks for reporting this issue. I will update this Github Issue when is fixed.

**Comment by guarinogabriel** [comment]
Hi there!

SpeedTest CLI (https://github.com/sivel/speedtest-cli) is required to run speed tests from the command line.
I updated the installation process so it specifically asks if you want to install the utility.

If you have any other issue, just let me know.

**Comment by pauljakobwhite** [comment]
im having this same issue with speedtest-cli installed? Any thoughts?
