### ISSUE TITLE
Could you add a temperature monitoring 

### ISSUE THREAD

**Issue by pahakalle** [guarinogabriel/mac-cli#29]
could be like the time or just a list of all the components and their temps

**Comment by scottwarren** [comment]
Something like: https://github.com/Chris911/iStats could be useful here

**Comment by guarinogabriel** [comment]
@pahakalle @scottwarren Thanks for your suggestion! That's a great idea.

I implemented the `mac temp` command:
![screen shot 2016-06-27 at 9 29 24 pm](https://cloud.githubusercontent.com/assets/1928452/16400078/9e1963bc-3cae-11e6-815d-3a36ac5c8a9a.png)
