### ISSUE TITLE
Modular Features

### ISSUE THREAD

**Issue by zetas** [guarinogabriel/mac-cli#3]
Is there any chance of having a local config or local plugin option? An optional source ~/.mac-cli.sh line would allow people to expand the functionality with additional features. It would allow developers to make plugins for the mac-cli system. Right now they'd have to modify the massive shell script. It would be really cool if the script was broken into modules so people could enable or disable certain features for speed and add new ones easily.

If this is something you're open to I would consider submitting a PR to make it more like oh-my-zsh.

**Comment by trevor-allen** [comment]
Modular functionality would be awesome, especially considering how some of the functionality here is not mac specific.

**Comment by guarinogabriel** [comment]
@zetas Absolutely! That is a fantastic idea. I would love to see your contribution on the project. I look forward for your PR!

**Comment by guarinogabriel** [comment]
@zetas Would you like to discuss about your idea through email? Just let me know. If you are working on the PR, then I look forward to it.

**Comment by zetas** [comment]
@guarinogabriel I'll shoot you an email so we can discuss. I haven't had time to start my PR yet, I wanted to see how you guys felt before attempting to essentially refactor your entire application ;)

**Comment by guarinogabriel** [comment]
I just want to let everyone know that @zetas and me will work on the modularity for the project.

**Comment by guarinogabriel** [comment]
Hey @zetas, do you have any update on this?

**Comment by guarinogabriel** [comment]
Hi everyone!

I have great news. Modularity and plugins have been added to the project! Now the project can be extended by adding new plugins or improving the plugins that already exist: [/mac-cli/plugins](https://github.com/guarinogabriel/mac-cli/tree/master/mac-cli/plugins)

You can check the updated project page to read about it and also to read about the updated installation process: [https://github.com/guarinogabriel/mac-cli](https://github.com/guarinogabriel/mac-cli)

Best regards.
Gabriel
