### ISSUE TITLE
how to turn off mac:time

### ISSUE THREAD

**Issue by booknara** [guarinogabriel/Mac-CLI#34]
Hello, 

I would like to turn off time display that was invoked by mac time (Show clock at top right position in Terminal/iTerm) because there is no command for disappearing the time display.

I know that it is possible to restart iTerm application to reset, but it is nice to have the feature. 

Thanks in advance,
Daehee

**Comment by guarinogabriel** [comment]
Hi Daehee,

I have an idea to implement this. Running `mac time` for the second time could hide the clock.
So, it will "toggle" the clock each time the command is run.

I will mark it as "enhancement" and it will be implement soon.
Thanks!

**Comment by booknara** [comment]
Hi Gabriel, 

Thank you for the reply and your solution looks good! 

I'm looking forward to your implementation. 

Thanks,
Daehee

**Comment by guarinogabriel** [comment]
Hi @booknara,

Could you please contribute to the project by adding this enhancement?

**Comment by rgcr** [comment]
#62
