### ISSUE TITLE
Install Settings

### ISSUE THREAD

**Issue by jacobkossman** [guarinogabriel/mac-cli#39]
I think a cool feature would be to set up the global variables (eg github account etc) on first install. So you don't have to go in to the file and update it manually.

Awesome utility! 👍

**Comment by silverbux** [comment]
just an addition maybe an ssh_config or .ssh_config just so wont have to enter server details, credentials and path everytime you sync.

👍

**Comment by guarinogabriel** [comment]
@jacobkossman @silverbux Thanks for your suggestions! That is definitely part of the roadmap for the project.

**Comment by guarinogabriel** [comment]
The installation process has been updated and it includes a wizard to setup each of the global variables:
[https://github.com/guarinogabriel/mac-cli](https://github.com/guarinogabriel/mac-cli)

Best regards.
Gabriel
