### ISSUE TITLE
Existing dependencies

### ISSUE THREAD

**Issue by zetas** [guarinogabriel/mac-cli#4]
I'm running through the install now and It looks like it's forcing download of dependencies that already exist. It should check to see if they are available before trying to re-install. In some cases the re-install will be blocked but in others it could wipe out custom configs or installations.

**Comment by guarinogabriel** [comment]
I agree with you. Checking each of the dependencies will be one of the improvements for the CLI.

**Comment by guarinogabriel** [comment]
The installation process has been updated and it checks now each of the dependencies on your mac: [https://github.com/guarinogabriel/mac-cli](https://github.com/guarinogabriel/mac-cli)

Best regards.
Gabriel

**Comment by rinasek** [comment]
Git and Python still get installed even though they exist on system.
