### ISSUE TITLE
Uninstallation Instructions?

### ISSUE THREAD

**Issue by jackmaney** [guarinogabriel/mac-cli#41]
I just bumped into mac-cli, and while it looks interesting, I'd be a bit more comfortable with installing it if there were a straightforward way to uninstall it. Could uninstall instructions please be added to the README?

Thank you for your time.

**Comment by jacobkossman** [comment]
```rm /usr/local/bin/mac```

**Comment by jackmaney** [comment]
Fair enough...given everything that happened during installation, it wasn't clear to me that uninstalling would be as simple as that.

**Comment by jacobkossman** [comment]
well a few other things are being installed, harmless to leave installed (afaik). though you can take a look at the requirements and the integrated projects and uninstall them one by one but it's a bit unneccesary
