### ISSUE TITLE
Error happened to YouCompleteMe for vim

### ISSUE THREAD

**Issue by zhangzhishan** [guarinogabriel/mac-cli#42]
Error happened to my vim YouCompleteMe after "brew install python", I don't know whether it is happened to others. There is python installed in Mac, why do you need to install python again?

**Comment by guarinogabriel** [comment]
Thanks for your comment. This will be fixed here: https://github.com/guarinogabriel/mac-cli/issues/4
Basically, the CLI will check if the dependencies already exist in the system.
