### ISSUE TITLE
MAMP Commands Broken with Custom MySQL Password

### ISSUE THREAD

**Issue by buffaloseven** [guarinogabriel/Mac-CLI#45]
The MAMP commands are set to utilize the default root password.

An additional `mamp_mysql_password` variable should be added with the default set to `root`. Additionally, the MAMP MySQL process is started/restarted with a non-root user.  Not particularly familiar but curious if that should be root instead.

**Comment by guarinogabriel** [comment]
@buffaloseven Thanks for your comment. I will add this MAMP variable soon. Also, the MAMP start / stop / restart commands will be improved as well.

**Comment by guarinogabriel** [comment]
Hi @buffaloseven ,

Have you tried setting your custom password on this variable: `mysql_password`?
