### ISSUE TITLE
Syntax Error running 'mac install:all'

### ISSUE THREAD

**Issue by Mantene** [guarinogabriel/mac-cli#46]
downloaded the latest version today and ran 'mac install:all' and it seemed to go well until all of the sudden I got the following: 
/usr/local/bin/mac: line 2042: syntax error near unexpected token `fi'
/usr/local/bin/mac: line 2042: `			fi'

The full output from the command is here: 
[mhood@bujold]~/Documents/Source/mac-cli$ mac install:all
Copying script to local folder...
Installing homebrew...
/usr/bin/ruby -e '$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)'
It appears Homebrew is already installed. If your intent is to reinstall you
should do the following before running this installer again:
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
The current contents of /usr/local are bin Cellar CODEOFCONDUCT.md etc Frameworks include lib Library LICENSE.txt McAfee opt README.md selenium share var .git .github .gitignore
Installing pip...
sudo easy_install pip
Password:
Searching for pip
Best match: pip 8.1.2
Adding pip 8.1.2 to easy-install.pth file
Installing pip script to /usr/local/bin
Installing pip2.7 script to /usr/local/bin
Installing pip2 script to /usr/local/bin

Using /usr/local/lib/python2.7/site-packages
Processing dependencies for pip
Finished processing dependencies for pip
Installing GIT...
brew install git
Warning: git-2.9.0 already installed
Installing pv (Pipe Viewer)...
brew install pv
Warning: pv-1.6.0 already installed
Installing Python...
brew install python
Warning: python-2.7.12 already installed
Copying script to local folder...
Installing homebrew...
/usr/bin/ruby -e '$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)'
It appears Homebrew is already installed. If your intent is to reinstall you
should do the following before running this installer again:
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
The current contents of /usr/local are bin Cellar CODEOFCONDUCT.md etc Frameworks include lib Library LICENSE.txt McAfee opt README.md selenium share var .git .github .gitignore
Installing Git...
brew install git
Warning: git-2.9.0 already installed
Installing pv (Pipe Viewer)...
brew install pv
Warning: pv-1.6.0 already installed
Installing Python...
brew install python
Warning: python-2.7.12 already installed
Installing fdupes...
brew install fdupes

Warning: fdupes-1.51 already installed
Installing mycli (MySQL CLI - https://github.com/dbcli/mycli)...
brew install mycli
Warning: mycli-1.7.0 already installed
Installing Compass...
gem install compass
Fetching: sass-3.4.22.gem (100%)
Successfully installed sass-3.4.22
Fetching: multi_json-1.12.1.gem (100%)
Successfully installed multi_json-1.12.1
Fetching: compass-core-1.0.3.gem (100%)
Successfully installed compass-core-1.0.3
Fetching: compass-import-once-1.0.5.gem (100%)
Successfully installed compass-import-once-1.0.5
Fetching: chunky_png-1.3.6.gem (100%)
Successfully installed chunky_png-1.3.6
Fetching: rb-fsevent-0.9.7.gem (100%)
Successfully installed rb-fsevent-0.9.7
Fetching: ffi-1.9.10.gem (100%)
Building native extensions.  This could take a while...
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ dir_s_mkdir - /usr/local/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0/ffi-1.9.10
Installing Glances (https://github.com/nicolargo/glances)...
pip install glances
Requirement already satisfied (use --upgrade to upgrade): glances in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): psutil>=2.0.0 in /Library/Python/2.7/site-packages (from glances)
Installing SpeedTest CLI (https://github.com/sivel/speedtest-cli)...
pip install speedtest-cli
Requirement already satisfied (use --upgrade to upgrade): speedtest-cli in /usr/local/lib/python2.7/site-packages
Installing N98 Magerun (https://github.com/netz98/n98-magerun)...
wget https://files.magerun.net/n98-magerun.phar
--2016-07-01 09:37:30--  https://files.magerun.net/n98-magerun.phar
Resolving files.magerun.net... 5.35.244.165
Connecting to files.magerun.net|5.35.244.165|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4107044 (3.9M) [application/octet-stream]
Saving to: ‘n98-magerun.phar’

n98-magerun.phar              100%[=================================================>]   3.92M  3.00MB/s    in 1.3s

2016-07-01 09:37:32 (3.00 MB/s) - ‘n98-magerun.phar’ saved [4107044/4107044]

chmod +x ./n98-magerun.phar
sudo mv ./n98-magerun.phar /usr/local/bin/
Password:
Installing N98 Magerun 2 (https://github.com/netz98/n98-magerun2)...
wget https://files.magerun.net/n98-magerun2.phar
--2016-07-01 09:37:38--  https://files.magerun.net/n98-magerun2.phar
Resolving files.magerun.net... 5.35.244.165
Connecting to files.magerun.net|5.35.244.165|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3854770 (3.7M) [application/octet-stream]
Saving to: ‘n98-magerun2.phar’

n98-magerun2.phar             100%[=================================================>]   3.68M  2.78MB/s    in 1.3s

2016-07-01 09:37:40 (2.78 MB/s) - ‘n98-magerun2.phar’ saved [3854770/3854770]

chmod +x ./n98-magerun2.phar
sudo mv ./n98-magerun2.phar /usr/local/bin/
Installing composer...
curl -sS https://getcomposer.org/installer | php
All settings correct for using Composer
Downloading 1.1.3...

Composer successfully installed to: /Users/mhood/Documents/Source/mac-cli/composer.phar
Use it: php composer.phar
sudo mv composer.phar /usr/local/bin/
Installing GIT cal (https://github.com/k4rthik/git-cal)...
brew install git-cal
Warning: git-cal-0.9.1 already installed
Installing ImageOptim...
brew cask install --appdir=~/Applications imageoptim --force
Warning: The default Caskroom location has moved to /usr/local/Caskroom.

Please migrate your Casks to the new location and delete /opt/homebrew-cask/Caskroom,
or if you would like to keep your Caskroom at /opt/homebrew-cask/Caskroom, add the
following to your HOMEBREW_CASK_OPTS:

  --caskroom=/opt/homebrew-cask/Caskroom

For more details on each of those options, see https://github.com/caskroom/homebrew-cask/issues/21913.
==> Downloading https://imageoptim.com/ImageOptim1.6.1.tar.bz2
Already downloaded: /Users/mhood/Library/Caches/Homebrew/imageoptim-1.6.1.tar.bz2
==> Verifying checksum for Cask imageoptim
==> It seems there is already an App at '/Users/mhood/Applications/ImageOptim.app'; overwriting.
==> Removing App: '/Users/mhood/Applications/ImageOptim.app'
==> Moving App 'ImageOptim.app' to '/Users/mhood/Applications/ImageOptim.app'
🍺  imageoptim staged at '/opt/homebrew-cask/Caskroom/imageoptim/1.6.1' (0B)
Installing ImageOptim-CLI (https://github.com/JamieMason/ImageOptim-CLI)...
npm install -g imageoptim-cli
/usr/local/bin/imageOptim -> /usr/local/lib/node_modules/imageoptim-cli/bin/imageOptim
/usr/local/bin/pngquant -> /usr/local/lib/node_modules/imageoptim-cli/bin/pngquant
/usr/local/bin/imageOptimBashLib -> /usr/local/lib/node_modules/imageoptim-cli/bin/imageOptimBashLib
/usr/local/bin/imageOptimAppleScriptLib -> /usr/local/lib/node_modules/imageoptim-cli/bin/imageOptimAppleScriptLib
/usr/local/lib
└── imageoptim-cli@1.14.8

Installing sass...
sudo gem install sass
Successfully installed sass-3.4.22
Parsing documentation for sass-3.4.22
Installing ri documentation for sass-3.4.22
Done installing documentation for sass after 12 seconds
1 gem installed
Installing storm (https://github.com/emre/storm)...
brew install stormssh
Warning: stormssh-0.6.7 already installed
Installing fdupes...
brew install fdupes

Warning: fdupes-1.51 already installed
Installing iStats...
sudo gem install iStats -n/usr/local/bin

Fetching: sparkr-0.4.1.gem (100%)
Successfully installed sparkr-0.4.1
Fetching: parseconfig-1.0.8.gem (100%)
Successfully installed parseconfig-1.0.8
Fetching: iStats-1.2.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed iStats-1.2.0
Parsing documentation for sparkr-0.4.1
Installing ri documentation for sparkr-0.4.1
Parsing documentation for parseconfig-1.0.8
Installing ri documentation for parseconfig-1.0.8
Parsing documentation for iStats-1.2.0
Installing ri documentation for iStats-1.2.0
Done installing documentation for sparkr, parseconfig, iStats after 0 seconds
3 gems installed
/usr/local/bin/mac: line 2042: syntax error near unexpected token `fi'
/usr/local/bin/mac: line 2042: `
[mhood@bujold]~/Documents/Source/mac-cli$

**Comment by guarinogabriel** [comment]
Hi @Mantene,

The installation process has been updated, you can check the project page to read about the new and improved installation process:
[https://github.com/guarinogabriel/mac-cli](https://github.com/guarinogabriel/mac-cli)

Best regards.
Gabriel
