### ISSUE TITLE
git/python should be detected when already installed with Xcode

### ISSUE THREAD

**Issue by tofi86** [guarinogabriel/mac-cli#47]
At the moment, git is being installed again from homebrew. Please fix that.

**Comment by tofi86** [comment]
same for python

**Comment by guarinogabriel** [comment]
@tofi86: Thanks for your comment. This will be fixed here: https://github.com/guarinogabriel/mac-cli/issues/4
Basically, the CLI will check if the dependencies already exist in the system.

**Comment by tofi86** [comment]
Ah, alright, perfect! :)
