### ISSUE TITLE
sed: 1: "/Volumes/Drive/username ...": extra characters at the end of D command

### ISSUE THREAD

**Issue by jacobkossman** [guarinogabriel/Mac-CLI#54]
Getting a sed error when attempting to change from vi to nano and the command is being repeated. I'd add a pull request but i don't have the expertise!

**Comment by jacobkossman** [comment]
i did a little research and i think it has to do with the ```sed -i``` command having to have ```sed -i ''```

**Comment by jacobkossman** [comment]
Fixed by #57

**Comment by guarinogabriel** [comment]
@jacobkossman Thanks for reporting the issue!
