### ISSUE TITLE
speedtest

### ISSUE THREAD

**Issue by IndexOutOfBound** [guarinogabriel/Mac-CLI#67]
Hi, i tried to do mac speedtest but apparantly its not working for me. I don't know if its just me...

$ mac speedtest
Do you want to install the Speed Test utility? (https://github.com/sindresorhus/speed-test) (Yes / No)Yes
/usr/local/bin/mac-cli/plugins/network: line 13: npm: command not found

**Comment by guarinogabriel** [comment]
Thanks for reporting this issue. Node has been added to the install process.

To fix that issue on your local machine, please install node using the following command:
`brew install node`

Then, you will be able to install the Speed Test utility.
