### ISSUE TITLE
Atom Package Manager

### ISSUE THREAD

**Issue by stockulus** [guarinogabriel/Mac-CLI#68]
Would it be ok, to include the atom package updates in the mac update command?

**Comment by guarinogabriel** [comment]
@stockulus Sure, please make sure to add a conditional to check if atom is installed to avoid running that updater if the user doesn't have Atom installed. I look forward to the PR! Thanks.

**Comment by guarinogabriel** [comment]
@stockulus Thank you for your contribution! 😃
