### ISSUE TITLE
Tool doesn´t work well

### ISSUE THREAD

**Issue by noetig** [guarinogabriel/Mac-CLI#74]
I installed your tool with the command you list in your github. I see the tool does not fit my needs. How can I remove it and make all changes back? There should be a guide somewhere ;)

**Comment by ctews** [comment]
I currently like it, but there's so much stuff that gets installed, I would also like to see a `mac uninstall` script to get rid of everything if needed.

**Comment by guarinogabriel** [comment]
Hi everyone!

You can uninstall Mac CLI by running:
`sh /usr/local/bin/mac-cli/tools/uninstall`

I will add that to the README file.
