### ISSUE TITLE
mac speedtest doesn't work as expected

### ISSUE THREAD

**Issue by ctews** [guarinogabriel/Mac-CLI#75]
Simple like that. If you type `mac speedtest` nothing happens, `mac speedtest:infinite` works :)

**Comment by mxeise** [comment]
same problem here, but for `mac speedtest:infinite` i was asked to install first

**Comment by metapixel** [comment]
Same here. And `mac info` doesn't work either.

**Comment by guarinogabriel** [comment]
@ctews @mxeise @metapixel 

Thanks for reporting this issue. This has been fixed on the following commit: https://github.com/guarinogabriel/Mac-CLI/commit/2f1c2b9c581167436d29d81987769702acbca512
You can update Mac CLI to have the fix installed by running:
`sh -c "$(curl -fsSL https://raw.githubusercontent.com/guarinogabriel/mac-cli/master/mac-cli/tools/upgrade)"`
