### ISSUE TITLE
Pyhton and Composer Update Fails with a Lot of Errors

### ISSUE THREAD

**Issue by benmarten** [guarinogabriel/Mac-CLI#77]
I am running the latest mac-cli version and everything works well, except updating python and composer packages.

I am getting a lot of errors: https://gist.github.com/benmarten/932a85322b990d43d55bde100ad5f9c3

Any ideas?

**Comment by guarinogabriel** [comment]
Hi Ben,

Those errors are not directly related to Mac CLI, those are related to the python and composer updaters.
I'll report the issue on those projects to receive feedback.

Best regards.
Gabriel
