### ISSUE TITLE
Uninstaller

### ISSUE THREAD

**Issue by ganesshkumar** [guarinogabriel/Mac-CLI#83]
Similar to the [install script](https://raw.githubusercontent.com/guarinogabriel/mac-cli/master/mac-cli/tools/install), is there an uninstall script available?

**Comment by guarinogabriel** [comment]
You can uninstall Mac CLI by running:

sh -c "$(curl -fsSL https://raw.githubusercontent.com/guarinogabriel/mac-cli/master/mac-cli/tools/uninstall)"
