### ISSUE TITLE
plugins/lamp "flaws"

### ISSUE THREAD

**Issue by andistern** [guarinogabriel/Mac-CLI#89]
generally Homebrew version uses local user as default without specifying a password, this option should be considered, using an aditional parameter would perhaps be a good idea, in lamp script a lot of `if` Statements would be necessary...
line 15:`         open -a /Applications/Sequel\ Pro.app` <-- dependency not specified
line 25:`         mycli  -u$mysql_user -p$mysql_password -S /Applications/MAMP/tmp/mysql/mysql.sock`
will not work with Hombrew version, use perhaps `-S $mysql_socket` instead
line 191:`        open /Applications/MAMP\ PRO/MAMP\ PRO.app/` <-- dependency not specified

**Comment by andistern** [comment]
line 40 should read`     "mysql:export")`

**Comment by guarinogabriel** [comment]
Thanks for your suggestion @andistern. If you can contribute to the project by adding those changes, that would be much appreaciated!

**Comment by andistern** [comment]
OK, but you should make the following design decision:
should the presence of lamp be detected at update/install time (in `update`/`install` ) or at runtime ( `lamp` script )?
