### ISSUE TITLE
How about mac awake

### ISSUE THREAD

**Issue by xjlin0** [guarinogabriel/Mac-CLI#9]
Great work and I really like it!

It' good to see mac sleep, how about integration of caffeine and make a **mac awake** (but screen can be off) for some computation moment with lid closed?

Thanks!

**Comment by guarinogabriel** [comment]
@xjlin0 Thank you! Glad that you like it.

Let me investigate that integration, I think it's a good idea. I'll update this Github Issue later.

**Comment by guarinogabriel** [comment]
Hi there!

I am closing this Github Issue since a contributor added the following command for the times you take a break away from your Mac: `mac lock`

Thanks a lot for your comment!
