### ISSUE TITLE
folders list command exits out

### ISSUE THREAD

**Issue by chrismccoy** [guarinogabriel/Mac-CLI#91]
following shows as error.

    awk: cmd (FILENAME=- FNR=1) fatal: function `secho' not defined

**Comment by guarinogabriel** [comment]
Thanks for reporting this issue.
It has been solved in the following commit: https://github.com/guarinogabriel/Mac-CLI/commit/bc6cc6c71671f935bf3531e0fc4487b4c69e4e2f
