### ISSUE TITLE
mac speedtest error

### ISSUE THREAD

**Issue by lfarah** [guarinogabriel/Mac-CLI#92]
<img width="767" alt="screen shot 2016-08-03 at 1 23 58 pm" src="https://cloud.githubusercontent.com/assets/6511079/17373221/9fe9f328-597d-11e6-9df1-601ddbd3242c.png">

**Comment by guarinogabriel** [comment]
Thanks for reporting this issue. This will be solved on the following GI: https://github.com/guarinogabriel/Mac-CLI/issues/90
