### ISSUE TITLE
Operation not permitted when installing SASS

### ISSUE THREAD

**Issue by Paradoxis** [guarinogabriel/Mac-CLI#94]
When installing SASS on my macbook, I keep a permission denied error. Example output:

```plain
Installing sass...
sudo gem install sass

ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/sass
```

**Comment by guarinogabriel** [comment]
Hi @Paradoxis,

Thanks for reporting this issue.
It has been resolved in the following commit: https://github.com/guarinogabriel/Mac-CLI/commit/4033b5892e2f14cfc4ccb4ac637515c7ff50dfa7

**Comment by Paradoxis** [comment]
Sweet, thanks
