### ISSUE TITLE
Error with the gem updating in the command mac update

### ISSUE THREAD

**Issue by pahakalle** [guarinogabriel/Mac-CLI#95]
ERROR:  Gem names are not allowed with the --system option

**Comment by guarinogabriel** [comment]
Could you please add more information related to the issue? Thanks!

**Comment by pahakalle** [comment]
Sorry for the lack of info and a late reply. but basically i get that error every time mac update runs the gem update part.
heres a picture of it: 
![screen shot 1](https://cloud.githubusercontent.com/assets/1533244/18300818/5963b984-74d5-11e6-95e7-53dea214b794.png)
